export const designMetrics = {
  iterationReduction: 40,
  timesSaved: 127,
  suggestionsGenerated: 1543,
  consistencyScore: 94,
}

export const recentSuggestions = [
  {
    id: 1,
    type: "Layout",
    title: "Optimize card spacing",
    description: "Increase vertical spacing between cards from 16px to 24px for better visual hierarchy",
    confidence: 92,
    timestamp: "2 minutes ago",
    status: "pending",
  },
  {
    id: 2,
    type: "Content",
    title: "Improve CTA copy",
    description: 'Change "Submit" to "Get Started" for higher conversion rates',
    confidence: 88,
    timestamp: "15 minutes ago",
    status: "applied",
  },
  {
    id: 3,
    type: "Visual",
    title: "Icon style mismatch",
    description: "Replace outlined icons with filled variants to match design system",
    confidence: 95,
    timestamp: "1 hour ago",
    status: "applied",
  },
  {
    id: 4,
    type: "Layout",
    title: "Responsive breakpoint",
    description: "Add tablet breakpoint at 768px for better mobile experience",
    confidence: 85,
    timestamp: "2 hours ago",
    status: "dismissed",
  },
]

export const allSuggestions = [
  {
    id: 1,
    type: "Layout",
    title: "Optimize card spacing",
    description: "Increase vertical spacing between cards from 16px to 24px for better visual hierarchy",
    rationale:
      "Current spacing creates visual tension. Increasing to 24px aligns with 8px grid system and improves scannability.",
    confidence: 92,
    timestamp: "2 minutes ago",
    status: "pending",
    impact: "high",
    before: "gap-4 (16px)",
    after: "gap-6 (24px)",
    affectedComponents: ["ProductCard", "FeatureCard", "TestimonialCard"],
  },
  {
    id: 2,
    type: "Content",
    title: "Improve CTA copy",
    description: 'Change "Submit" to "Get Started" for higher conversion rates',
    rationale:
      'Generic "Submit" lacks motivation. "Get Started" creates action-oriented language and reduces friction.',
    confidence: 88,
    timestamp: "15 minutes ago",
    status: "applied",
    impact: "medium",
    before: '"Submit"',
    after: '"Get Started"',
    affectedComponents: ["SignupForm", "ContactForm"],
  },
  {
    id: 3,
    type: "Visual",
    title: "Icon style mismatch",
    description: "Replace outlined icons with filled variants to match design system",
    rationale:
      "Design system specifies filled icons for primary actions. Current outlined style creates inconsistency.",
    confidence: 95,
    timestamp: "1 hour ago",
    status: "applied",
    impact: "high",
    before: "outline variant",
    after: "filled variant",
    affectedComponents: ["Navigation", "ActionButtons", "FeatureIcons"],
  },
  {
    id: 4,
    type: "Layout",
    title: "Responsive breakpoint",
    description: "Add tablet breakpoint at 768px for better mobile experience",
    rationale: "Current layout jumps from mobile to desktop. Tablet breakpoint provides smoother transition.",
    confidence: 85,
    timestamp: "2 hours ago",
    status: "dismissed",
    impact: "medium",
    before: "sm:grid-cols-1 lg:grid-cols-3",
    after: "sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3",
    affectedComponents: ["ProductGrid", "BlogGrid"],
  },
  {
    id: 5,
    type: "Content",
    title: "Simplify headline",
    description: "Reduce headline from 18 words to 8 words for better clarity",
    rationale: "Long headlines reduce comprehension. Shorter, punchier copy improves message retention by 40%.",
    confidence: 90,
    timestamp: "3 hours ago",
    status: "pending",
    impact: "high",
    before: "Transform your entire design workflow with AI-powered...",
    after: "AI-Powered Design Assistant for Modern Teams",
    affectedComponents: ["HeroSection"],
  },
  {
    id: 6,
    type: "Visual",
    title: "Increase contrast ratio",
    description: "Update secondary text color to meet WCAG AA standards",
    rationale: "Current contrast ratio is 3.8:1. WCAG AA requires 4.5:1 for accessibility compliance.",
    confidence: 98,
    timestamp: "4 hours ago",
    status: "pending",
    impact: "high",
    before: "#6B7280 (gray-500)",
    after: "#4B5563 (gray-600)",
    affectedComponents: ["BodyText", "Descriptions", "Captions"],
  },
  {
    id: 7,
    type: "Layout",
    title: "Align button sizes",
    description: "Standardize all primary buttons to 'lg' size for consistency",
    rationale: "Mixed button sizes (md, lg) create visual inconsistency. Standardizing improves UI coherence.",
    confidence: 87,
    timestamp: "5 hours ago",
    status: "applied",
    impact: "medium",
    before: "size='md' and size='lg'",
    after: "size='lg'",
    affectedComponents: ["CTAButtons", "FormButtons"],
  },
  {
    id: 8,
    type: "Content",
    title: "Add microcopy to form",
    description: "Include helper text below email input for clarity",
    rationale: "Users hesitate without guidance. Helper text reduces form abandonment by 23%.",
    confidence: 84,
    timestamp: "6 hours ago",
    status: "pending",
    impact: "medium",
    before: "No helper text",
    after: '"We\'ll never share your email with anyone else."',
    affectedComponents: ["SignupForm", "NewsletterForm"],
  },
]

export const generatedContent = [
  {
    id: 1,
    type: "Headline",
    content: "Transform Your Design Workflow",
    context: "Hero section for SaaS landing page",
    variations: 3,
  },
  {
    id: 2,
    type: "Button Text",
    content: "Start Free Trial",
    context: "Primary CTA button",
    variations: 5,
  },
  {
    id: 3,
    type: "Description",
    content: "Automate repetitive design tasks and focus on what matters most - creating exceptional user experiences.",
    context: "Feature card description",
    variations: 4,
  },
]

export const consistencyChecks = [
  {
    id: 1,
    category: "Typography",
    issue: "Font size inconsistency",
    details: "3 instances of 15px text found. Design system uses 14px and 16px.",
    severity: "medium",
    locations: ["Header navigation", "Footer links", "Sidebar menu"],
  },
  {
    id: 2,
    category: "Color",
    issue: "Off-brand color usage",
    details: "Using #4A5FFF instead of primary color #4F46E5",
    severity: "high",
    locations: ["CTA button", "Link hover states"],
  },
  {
    id: 3,
    category: "Spacing",
    issue: "Inconsistent padding",
    details: "Cards using 20px, 24px, and 28px padding. Standardize to 24px.",
    severity: "low",
    locations: ["Feature cards", "Testimonial cards", "Pricing cards"],
  },
]

export const aiModels = [
  {
    name: "GPT-4",
    purpose: "Design rationale & content generation",
    status: "active",
    requests: 1247,
  },
  {
    name: "CoreML Vision",
    purpose: "Icon & image style recognition",
    status: "active",
    requests: 892,
  },
]
